Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Creating order for user 2 with payment method razorpay
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 584, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
Error in razorpay_order_creation: name 'time' is not defined
Error in razorpay_order_creation: name 'time' is not defined
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Creating order for user 2 with payment method razorpay
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 583, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Resetting dropped connection: api.razorpay.com
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Creating order for user 2 with payment method razorpay
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 583, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Creating order for user 2 with payment method razorpay
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 586, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Order creation failed.
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Creating order for user 2 with payment method razorpay
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 588, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 679, in create_order
    customer=Customer.objects.get(user=request.user),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 679, in create_order
    customer=Customer.objects.get(user=request.user),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Creating order with address_id=1, coupon_code=None, discount=0, payment_method=razorpay
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 593, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Creating order with address_id=1, payment_method=razorpay, coupon_code=None
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 587, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/checkout
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 448, in checkout
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Error creating Razorpay order: customer/razorpay_checkout.html
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py", line 40, in razorpay_order_creation
    return render(request, "customer/razorpay_checkout.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/razorpay_checkout.html
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Error creating Razorpay order: customer/razorpay_checkout.html
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py", line 40, in razorpay_order_creation
    return render(request, "customer/razorpay_checkout.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/razorpay_checkout.html
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 569, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Watching for file changes with StatReloader
Not Found: /favicon.ico
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 569, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Watching for file changes with StatReloader
Not Found: /favicon.ico
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Error during order creation: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 569, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Internal Server Error: /customer/finalize-order/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 633, in finalize_order
    order = create_order(request)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 568, in create_order
    customer = Customer.objects.get(user=request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: account_ptr, account_ptr_id, address, approved, cart, customercoupon, date_joined, email, favouriteitem, first_name, id, is_active, is_admin, is_customer, is_staff, is_superadmin, last_login, last_name, logentry, mobile, order, password, payment, profile_image, wallet
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/order-confirmation/22/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 675, in order_confirmation
    return render(request, "customer/order-confirmation.html", {'order': order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/order-confirmation.html
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/order-confirmation/22/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 675, in order_confirmation
    return render(request, "customer/order-payment.html", {'order': order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/order-payment.html
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/order-confirmation/22/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 665, in order_confirmation
    order = Order.objects.filter(id=order_id, customer__user=request.user).first()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'user' for ForeignKey or join on the field not permitted.
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Internal Server Error: /payment/razorpay-order-creation/1823/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1428, in getresponse
    response.begin()
  File "C:\Users\Anand\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1428, in getresponse
    response.begin()
  File "C:\Users\Anand\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py", line 30, in razorpay_order_creation
    razorpay_order = razorpay_client.order.create(data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\razorpay\resources\order.py", line 71, in create
    return self.post_url(url, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\razorpay\resources\base.py", line 20, in post_url
    return self.client.post(url, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\razorpay\client.py", line 156, in post
    return self.request('post', path, data=data, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\razorpay\client.py", line 120, in request
    response = getattr(self.session, method)(url, auth=self.auth,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Starting new HTTPS connection (2): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Internal Server Error: /customer/order-confirmation/23/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 665, in order_confirmation
    order = Order.objects.filter(id=order_id, customer__user=request.user).first()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'user' for ForeignKey or join on the field not permitted.
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/order-confirmation/23/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 677, in order_confirmation
    return render(request, "customer/order-confirmation.html", {'order': order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/order-confirmation.html
Internal Server Error: /customer/order-confirmation/23/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 677, in order_confirmation
    return render(request, "customer/order-confirmation.html", {'order': order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/order-confirmation.html
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Internal Server Error: /aadmin/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 25, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 62, in admin_dashboard
    product = Product.objects.get(id=product_info["product__id"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
product.models.Product.DoesNotExist: Product matching query does not exist.
Forbidden (CSRF token from POST incorrect.): /account/admin-login/
Internal Server Error: /aadmin/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 25, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 62, in admin_dashboard
    product = Product.objects.get(id=product_info["product__id"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
product.models.Product.DoesNotExist: Product matching query does not exist.
Not Found: /aa
Internal Server Error: /aadmin/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 25, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 62, in admin_dashboard
    product = Product.objects.get(id=product_info["product__id"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
product.models.Product.DoesNotExist: Product matching query does not exist.
Internal Server Error: /aadmin/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 25, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 62, in admin_dashboard
    product = Product.objects.get(id=product_info["product__id"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
product.models.Product.DoesNotExist: Product matching query does not exist.
Not Found: /favicon.ico
Not Found: /cancel_order/23/
Watching for file changes with StatReloader
Not Found: /favicon.ico
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Internal Server Error: /customer/order-confirmation/24/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 677, in order_confirmation
    return render(request, "customer/order-confirmation.html", {'order': order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/order-confirmation.html
Internal Server Error: /customer/order-confirmation/24/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 677, in order_confirmation
    return render(request, "customer/order-confirmation.html", {'order': order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customer/order-confirmation.html
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/order-confirmation/24/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view customer.views.order_confirmation didn't return an HttpResponse object. It returned None instead.
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Internal Server Error: /aadmin/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 25, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 62, in admin_dashboard
    product = Product.objects.get(id=product_info["product__id"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
product.models.Product.DoesNotExist: Product matching query does not exist.
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Internal Server Error: /customer/order-confirmation/25/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view customer.views.order_confirmation didn't return an HttpResponse object. It returned None instead.
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 210
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /customer/place_order
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 513, in place_order
    total_offer = sum(
                  ^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 515, in <genexpr>
    (CategoryOffer.objects.filter(category=cart_item.product.main_category).first().discount / 100))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'discount'
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Not Found: /cancel_order/21/
Internal Server Error: /shop/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\home\views.py", line 77, in shop
    products = products.order_by("price")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\query.py", line 1701, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 2249, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'price' into field. Choices are: approved, cartitem, created_at, deleted_at, description, favouriteitem, id, inventory_sizes, is_available, is_deleted, last_modified_at, main_category, main_category_id, mrp, name, orderitem, product_images, slug, subcategories
C:\Users\Anand\Desktop\Anand\Amart\ecom\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\home\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /cancel_order/29/
Not Found: /cancel_order/29/
Not Found: /cancel_order/29/
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /cancel_order/21/
Not Found: /cancel_order/25/
Not Found: /cancel_order/25/
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 214
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /cancel_order/32/
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /customer/wallet
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 724, in customer_wallet
    return render(request, "customer/customer-wallet.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 151: 'endblock'. Did you forget to register or load this tag?
Starting new HTTPS connection (1): api.razorpay.com:443
Starting new HTTPS connection (2): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 206
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 206
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 206
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 206
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 210
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 214
Forbidden (CSRF token from POST incorrect.): /shop/
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\payment\views.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 211
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "GET /v1/orders/order_OxhBxy9M8SMWkf HTTP/11" 200 None
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 211
https://api.razorpay.com:443 "GET /v1/orders/order_OxhEb809lC3wUc HTTP/11" 200 None
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 217
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 217
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 215
https://api.razorpay.com:443 "GET /v1/orders/order_OxhI77a3oTzQJW HTTP/11" 200 None
Resetting dropped connection: api.razorpay.com
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 215
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 215
Resetting dropped connection: api.razorpay.com
https://api.razorpay.com:443 "GET /v1/orders/order_Oxhog0FAlbORMF HTTP/11" 200 None
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/checkout
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 517, in checkout
    "wallet_amount": wallet.amount if wallet else 0,  # Pass wallet amount to template
                     ^^^^^^^^^^^^^
AttributeError: 'Wallet' object has no attribute 'amount'
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /customer/checkout
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py", line 484, in checkout
    customer = request.user.customerprofile
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Account' object has no attribute 'customerprofile'
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 212
Starting new HTTPS connection (1): api.razorpay.com:443
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 213
https://api.razorpay.com:443 "POST /v1/orders HTTP/11" 200 213
Starting new HTTPS connection (2): api.razorpay.com:443
https://api.razorpay.com:443 "GET /v1/orders/order_OxjJNgBYkYTfcz HTTP/11" 200 None
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\customer\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /aadmin/product/edit/1/
Not Found: /aadmin/product/edit/1/
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /aadmin/product/edit/1/
Not Found: /aadmin/product/edit/1/
Not Found: /aadmin/product/edit/1/
Not Found: /aadmin/product/edit/1/
Not Found: /aadmin/product/edit/1/
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /aadmin/product/edit/1/
Not Found: /aadmin/product/edit/1/
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /aadmin/product/edit/1/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 25, in wrapper
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py", line 448, in edit_product
    return render(request, "aadmin/product-edit-form.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'remove_product_image' not found. 'remove_product_image' is not a valid view function or pattern name.
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /aadmin/inventory/edit/2/
Traceback (most recent call last):
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Anand\Desktop\Anand\Amart\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view aadmin.views.wrapper didn't return an HttpResponse object. It returned None instead.
C:\Users\Anand\Desktop\Anand\Amart\ecom\aadmin\views.py changed, reloading.
Watching for file changes with StatReloader
